DELETE TABLE IF EXISTS Contents;
DELETE TABLE IF EXISTS Categories;
DELETE TABLE IF EXISTS Tags;
DELETE TABLE IF EXISTS Attachments;
DELETE TABLE IF EXISTS ContentsCategoriesTh;
DELETE TABLE IF EXISTS ContentsTagsTh;
DELETE TABLE IF EXISTS ContentsAttachmentsTh;

