DROP TABLE IF EXISTS Contents; 
DROP TABLE IF EXISTS Categories; 
DROP TABLE IF EXISTS Tags; 
DROP TABLE IF EXISTS Attachments; 
DROP TABLE IF EXISTS ContentsCategoriesTh; 
DROP TABLE IF EXISTS ContentsTagsTh; 
DROP TABLE IF EXISTS ContentsAttachmentsTh; 